   <Style Type='text/css'>
      Td, { font-size: 9pt; font-family: ±¼¸²; color: #333333; }

      A:link    { color:black; text-decoration:none }
      A:active  { color:blue;  text-decoration:none }
      A:visited { color:blue;  text-decoration:none }
      A:hover   { color:gray;  text-decoration:none }

      .writeinput { height: 20px; border-width: 1; font-size: 9pt; border-style: ridge; border-color: #d0d0d0; background-color: #ffffff;}
      .writetext  { height: 255px; border-width: 1; font-size: 9pt; border-style: ridge; border-color: #d0d0d0; background-color: #ffffff;}
      .writebutton{ height: 20px; border-width: 1; font-size: 8pt; border-style: ridge; border-color: #d0d0d0; background-color: #dfdfdf;}

      .joinsinput { height: 20px; border-width: 1; font-size: 9pt; border-style: ridge; border-color: #d0d0d0; background-color: #ffffff;}
      .joinsbutton{ height: 20px; border-width: 2; font-size: 8pt; border-style: ridge; border-color: #d0d0d0; background-color: #dfdfdf;}
   </Style>
