   <!-- Copyright -- ½ÃÀÛ ---------------------->

   <Table Width="100%" Height="40" Cellpadding="0" Cellspacing="0" Border="0">
      <Tr><Td Align="center" Valign="center">
         <Span Style="Font-Size: 8pt"><B>
         Copyright 2000-2001 <A Href="http://workspace.ye.ro" Target='_blank'>WorkSpace.</A> All rights reserved
         </B></Span>
      </Td></Tr>
   </Table>

   <!-- Copyright -- ³¡ ------------------------>
