<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<pre style='float:right;top:0px;left:0px;display:<%=(SELF_URL.indexOf("toplus.kr") > 0?"none":"inline")%>'>
<!-- <a href="/sub.jsp?p_m=1&p_s=1">    Just English란?     </a>
<a href="/sub.jsp?p_m=2&p_s=1">    스터디존            </a>
<a href="/sub.jsp?p_m=2&p_s=1">        내신 Zone       </a>
<a href="/sub.jsp?p_m=2&p_s=2">        Voca Zone       </a>
<a href="/sub.jsp?p_m=2&p_s=3">        Grammar Zone    </a>
<a href="/sub.jsp?p_m=2&p_s=4">        Test Zone       </a>

<a href="/sub.jsp?p_m=3&p_s=1">    교육정보            </a>
<a href="/sub.jsp?p_m=3&p_s=1">        교육뉴스        </a>
<a href="/sub.jsp?p_m=3&p_s=2">        특목뉴스        </a>
<a href="/sub.jsp?p_m=3&p_s=3">        학원게시판      </a>

<a href="/sub.jsp?p_m=4&p_s=1">    고객센터            </a>
<a href="/sub.jsp?p_m=4&p_s=1">        공지사항        </a>
<a href="/sub.jsp?p_m=4&p_s=2">        오류신고        </a>
<a href="/sub.jsp?p_m=4&p_s=3">        자주묻는 질문   </a>
<a href="/sub.jsp?p_m=4&p_s=4">        원격지원서비스  </a>
<a href="/sub.jsp?p_m=4&p_s=5">        가맹문의        </a>
 --><div id=_info></div>
</pre>
</body>
</html>

