<%
/**
 * 
 * Filename        : /inc/header.inc
 * Fuction         : 헤더
 * Comment         : 
 * 시작 일자       : 2010-12-10,
 * 수정 일자       : 2010-12-20, Kim. JiHoon v1.0 first
 * 작 성 자        : 김 지 훈
 * 수 정 자        :
 * @version        : 1.0
 * @author         : Copyright (c) ~
*/
%>
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title><%=SITE_TITLE%></title>
<!-- <meta http-equiv="Content-Type" content="text/html; charset=euc-kr"> -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Cache-Control" content="no-cache"/>
<meta http-equiv="Expires" content="0"/>
<meta http-equiv="Pragma" content="no-cache"/>
<link href="<%=BASE_ROOT%>css/style.css" rel="stylesheet" type="text/css">

<script language="javascript" type="text/javascript" src="<%=BASE_ROOT%>js/jquery-1.7.1.min.js"></script>
<script language="javascript" type="text/javascript" src="<%=BASE_ROOT%>js/softm.jsp.js"></script>
<script language="javascript" type="text/javascript" src="<%=BASE_ROOT%>js/json2.js"></script>
<script language="javascript" type="text/javascript" src="<%=BASE_ROOT%>js/common.js"></script>

<!-- 플래시 스크립트 시작 -->
<script language="javascript" src="<%=BASE_ROOT%>flash/flash_activate.js"></script>
<script language="javascript" src="<%=BASE_ROOT%>flash/flash_link.js"></script>
<!-- 플래시 스크립트 끝 -->
<SCRIPT LANGUAGE="JavaScript">
<!--
    var SITE_ID   = "ORADMS";
    var REST_ROOT = "<%=REST_ROOT%>";
//-->
</SCRIPT>
</head>
