<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php 
if ( BROWSER == 'msie' ) {
?>
<!-- <script type="text/javascript"  -->
<!-- src="https://getfirebug.com/firebug-lite.js"> -->
<!-- {
    overrideConsole: false,
    startInNewWindow: true,
    startOpened: true,
    enableTrace: true
} -->
<!-- </script> -->
<?php 
}
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<meta http-equiv="Cache-Control" content="no-cache">
<!-- <title>한일산업기술통합정보시스템</title> -->
<title></title>
<link rel='stylesheet' href='<?=HTTP_URL?>/include/default.css' type='text/css'>
<!-- <link rel='stylesheet' href='<?=HTTP_URL?>/include/layout.css' type='text/css'>-->
<!-- <link rel=stylesheet href='/css/softm.css' type='text/css'/>
<link rel=stylesheet href='/test/css_table/styletable.css' type='text/css'/> -->

<script language="javascript" src="<?=HTTP_URL?>/include/inc_common.js"></script>
<script language="javascript" src="<?=HTTP_URL?>/include/flashwrite.js"></script>
<!--[if IE]>
<style type="text/css">
.textOf {overflow:hidden;text-overflow:ellipsis;}
</style>
<![endif]-->
<script type="text/javascript">
<!--
var p_hash   = '<?=md5('xltpszmfnvm' . date ("Y-m-d"))?>';
var LOGIN     = <?=LOGIN?"true":"false"?>;
var ADMIN     = <?=ADMIN?"true":"false"?>;
var USER_LEVEL= "<?=USER_LEVEL?>";
var USER_NO   = "<?=USER_NO?>";
var USER_ID   = "<?=USER_ID?>";
var COMPANY_NO= "<?=COMPANY_NO?>";
//-->
</script>
<!-- <script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/js/softm.js"></script>
 -->
<script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/service/js/asyncConnector.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/service/js/jquery-1.7.1.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/service/js/softm.jquery.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/service/js/softm.grid.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/service/js/json2.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=HTTP_URL?>/service/js/jquery.zclip.js"></script>
</HEAD>

<BODY>
