/* 사용자 */
DROP TABLE USER;
/* 코드 */
DROP TABLE CODE;
/* 고객센터 */
DROP TABLE AREA_CENTER;
/* 공급자 */
DROP TABLE PROVIDER;
/* 중계검침 */
DROP TABLE GUM;
/* 검침생성일자 */
DROP TABLE GUM_CREATE_DT;
/* 중계검침고객정보수정 */
DROP TABLE GUM_CUST;
