<?
/* 테이블 정보 */
define ('TBL_MEMBER'            , 'tbl_member'          ); // 회원
define ('TBL_PROC_CD'           , 'tbl_proc_cd'         ); // 대공종코드
define ('TBL_PROC_IT_CD'        , 'tbl_proc_it_cd'      ); // 공종항목코드
define ('TBL_PROC_BD_CD'        , 'tbl_proc_bd_cd'      ); // 공종항목내역코드
define ('TBL_REG_INFO'          , 'tbl_reg_info'        ); // 등록정보
define ('TBL_QNA'               , 'tbl_qna'             ); // 질문답변
define ('TBL_FILE'              , 'tbl_file'            ); // 첨부파일
define ('TBL_BBS_DATA_NOTICE'   , 'tbl_bbs_data_notice' ); // 첨부파일
?>