<!DOCTYPE html>
<html lang="ko">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<title>개발-프레임.</title>
<link rel="stylesheet" type="text/css" href="<?=SERVICE_URL?>/css/content.css" />
<script language="Javascript1.2" type="text/javascript" src="<?=SERVICE_URL?>/js/jquery-1.7.1.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=SERVICE_URL?>/js/softm.jquery.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=SERVICE_URL?>/js/softm.grid.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=SERVICE_URL?>/js/json2.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=SERVICE_URL?>/js/jquery.zclip.js"></script>
<script language="Javascript1.2" type="text/javascript" src="<?=SERVICE_URL?>/js/common.js"></script>
<script type="text/javascript">
<!--
var p_hash   = '<?=md5('rlawlgns' . date ("Y-m-d"))?>';
var LOGIN     = <?=LOGIN?"true":"false"?>;
var ADMIN     = <?=ADMIN?"true":"false"?>;
var USER_LEVEL= "<?=USER_LEVEL?>";
var USER_NO   = "<?=USER_NO?>";
var USER_ID   = "<?=USER_ID?>";
var COMPANY_NO= "<?=COMPANY_NO?>";
var SERVICE_BASE = "<?=SERVICE_BASE?>";
//-->
</script>
</HEAD>

<BODY>
