/* 사용자 */
CREATE TABLE USER (
	USER_ID TEXT NOT NULL, /* 아이디 */
	USER_NM TEXT NOT NULL, /* 사용자명 */
	PW TEXT NOT NULL, /* 비밀번호 */
	DEPT_CD TEXT, /* 부서코드 */
	HP_NO TEXT, /* 휴대전화번호 */
	LEVEL_CD TEXT, /* 관리레벨코드 */
	PW_CHANGE_DT TEXT, /* 비밀번호갱신일자 */
	PDA_USER_YN TEXT NOT NULL, /* 현장지원사용자여부 */
	AREA_CENTER_CD TEXT, /* 고객센터코드 */
	GUM_AUTH_YN TEXT NOT NULL, /* 검침권한여부 */
	CHG_AUTH_YN TEXT NOT NULL, /* 교체권한여부 */
	CHK_AUTH_YN TEXT NOT NULL, /* 점검권한여부 */
	REQ_AUTH_YN TEXT NOT NULL, /* 민원권한여부 */
	DEF_AUTH_YN TEXT NOT NULL, /* 체납권한여부 */

	PRIMARY KEY (
		USER_ID
	)
);

/* 코드 */
CREATE TABLE CODE (
	TYPE_CD TEXT NOT NULL, /* 구분코드 */
	CD TEXT NOT NULL, /* 코드 */
	CD_NM TEXT NOT NULL, /* 코드명 */
	MGT_CHAR1 TEXT, /* 관리문자1 */
	MGT_CHAR2 TEXT, /* 관리문자2 */
	MGT_CHAR3 TEXT, /* 관리문자3 */
	MGT_CHAR4 TEXT, /* 관리문자4 */
	MGT_CHAR5 TEXT, /* 관리문자5 */
	MGT_CHAR6 TEXT, /* 관리문자6 */
	MGT_NUM1 NUMERIC, /* 관리숫자1 */
	MGT_NUM2 NUMERIC, /* 관리숫자2 */
	ORD INTEGER, /* 정렬 */
	REMARK TEXT, /* 비고 */

	PRIMARY KEY (
		TYPE_CD, 
		CD
	)
);

Create TABLE CHG(
GM_CHG_YM VARCHAR2(6) NOT NULL
,HOUSE_NO VARCHAR2(14) NOT NULL
,CUST_NO VARCHAR2(10) NOT NULL
,EQUIP_CD VARCHAR2(20)
,AREA_CD VARCHAR2(1)
,SECTOR_CD VARCHAR2(3)
,COMPLEX_CD VARCHAR2(7)
,BLDG_CD VARCHAR2(10)
,HOUSE_ORD INTEGER
,AREA_NM VARCHAR2(50)
,SECTOR_NM VARCHAR2(50)
,COMPLEX_NM VARCHAR2(50)
,BLDG_NM VARCHAR2(50)
,BLDG_NO VARCHAR2(50)
,ROOM_NO VARCHAR2(50)
,ROAD_NM VARCHAR2(80)
,CUST_NM VARCHAR2(50)
,CO_NM VARCHAR2(50)
,TEL_NO VARCHAR2(20)
,HP_NO VARCHAR2(20)
,WORK_TEL_NO VARCHAR2(30)
,TEL_CD VARCHAR2(20)
,STATUS_CD VARCHAR2(20)
,CLAIM_CUST_YN CHAR(1)
,CLAIM_CONTENT VARCHAR2(500)
,CHE_MONTH_CNT NUMBER
,CHE_PRICE_SUM NUMBER
,GM_ERROR_YN CHAR(1)
,BF_GM_NO VARCHAR2(20)
,BF_MODEL VARCHAR2(100)
,BF_KIND_CD VARCHAR2(20)
,BF_TYPE_CD VARCHAR2(20)
,BF_MAKER_CD VARCHAR2(20)
,BF_INSTALL_LOC_CD VARCHAR2(20)
,BF_MAKE_YY VARCHAR2(4)
,BF_UNION_CNT INTEGER
,BF_SEAL_NO VARCHAR2(30)
,BF_REPAIR_CD VARCHAR2(20)
,BF_SEAL_CD VARCHAR2(20)
,BF_INSTALL_DT text
,AF_GM_NO VARCHAR2(20)
,AF_MODEL VARCHAR2(100)
,AF_KIND_CD VARCHAR2(20)
,AF_TYPE_CD VARCHAR2(20)
,AF_MAKER_CD VARCHAR2(20)
,AF_INSTALL_LOC_CD VARCHAR2(20)
,AF_MAKE_YY VARCHAR2(4)
,AF_UNION_CNT INTEGER
,AF_SEAL_NO VARCHAR2(30)
,AF_REPAIR_CD VARCHAR2(20)
,AF_SEAL_CD VARCHAR2(20)
,CHG_REMOVE_METER INTEGER
,CHG_INSTALL_METER INTEGER
,CHG_DT text
,CHG_USER_CD VARCHAR2(20)
,END_YN CHAR(1) DEFAULT 'N'
,SIGN_FILE_NM VARCHAR2(50)
,PHOTO_FILE_NM VARCHAR2(50)
,SEND_YN CHAR(1) DEFAULT 'N'
,BF_CHG_DT text
, Primary Key(GM_CHG_YM,HOUSE_NO,CUST_NO)
) ;

Create  TABLE CHG_CUST (
    GM_CHG_YM VARCHAR2(6) NOT NULL
    ,HOUSE_NO VARCHAR2(14) NOT NULL
    ,CUST_NO VARCHAR2(10) NOT NULL
    ,CUST_NM VARCHAR2(50)
    ,TEL_NO VARCHAR2(30)
    ,WORK_TEL_NO VARCHAR2(30)
    ,HP_NO VARCHAR2(30)
    ,TEL_CD VARCHAR2(20)
    ,SEND_YN CHAR(1) DEFAULT 'N'
    , Primary Key(GM_CHG_YM,HOUSE_NO,CUST_NO)
) ;

PRAGMA user_version = 2;