<?php 
// 게시판
$tb_bbs_infor           = "kyh_bbs_infor"   ;
$tb_bbs_category        = "kyh_bbs_category";
$tb_bbs_abstract        = "kyh_bbs_abstract";
$tb_bbs_skin            = "kyh_bbs_skin"    ;
$tb_bbs_grant           = "kyh_bbs_grant"   ;
$tb_point_infor         = "kyh_point_infor" ;
$tb_bbs_data            = "kyh_bbs_data"    ;
$tb_bbs_comment         = "kyh_bbs_comment" ;

$tb_bbs_file            = "kyh_bbs_file"    ;

// 이벤트
$tb_event               = "kyh_event";
$tb_event_grant         = "kyh_event_grant";
$tb_event_item          = "kyh_event_item";
$tb_event_result_master = "kyh_event_result_master";
$tb_event_result_detail = "kyh_event_result_detail";

// 회원
/** @var 회원기본정보 */ 
$tb_member              = "kyh_member";
$tb_member_kind         = "kyh_member_kind";
$tb_member_config       = "kyh_member_config";
$tb_login_abstract      = "kyh_login_abstract";
$tb_dic_member_statistic= "kyh_dic_member_statistic";

// 우편번호
$tb_post                = "kyh_post";

// 설문
$tb_poll_master         = "kyh_poll_master";
$tb_poll_item           = "kyh_poll_item";
$tb_poll_skin           = "kyh_poll_skin";
$tb_poll_grant          = "kyh_poll_grant";
$tb_poll_comment        = "kyh_poll_comment";
$tb_poll_point_infor    = "kyh_poll_point_infor";
?>